### PR TITLE
Templatize so it works both before and after RMW changes

### PR DESCRIPTION
**Pull request by rotu**
Note that the `extern "C"` declarations in this file are quite unnecessary - due to the rmw.h header, the declared interface will have C linkage (though there may be additional overloads that use C++ linkage)

### CODE REVIEW

**Comment by eboasson** [comment]
This is awesome! It's a busy day and I haven't had a chance to try it out properly, but let's see if I actually understand what it does ...

If it's the "old" interface, the ``rmw_subscription_options_t`` and ``rmw_publication_options_t`` don't exist, so there is no reference to functions with the "new" signature, and the templates don't get emitted.

If it is the "new" interface, then defining the old version is an overloaded variant that isn't affected by the ``extern "C"`` bit, and so is effectively simply an internal function. But it that case the ``extern "C"`` declaration of the new interface forces the expansion of the template.

Or something like that ... I suppose ... I'm not very good with the behaviour of C++ templates ...

Tomorrow I should have a chance to look at it more closely.

**Comment by rotu** [comment]
Thanks! I did this because I wanted to learn/practice SFINAE and templates in general.

You’re exactly right. `extern “C”` specifies which overload gets called when a C program asks for the function by name.

The other gotcha is, even in the template that doesn’t get instantiated, `rmw_subscription_t::option` doesn’t exist, so you *must* resolve it via a template type parameter `T_rmw_subscription::options` instead of the concrete `rmw_subscription_t::options`

**Comment by rotu** [comment]
Had to change function definition order so the new API functions can call the old API functions. Oops.

**Comment by eboasson** [comment]
@rotu I am very sorry that I have to tell you that on Eloquent with macOS the templating gives problems ... it compiles and links cleanly, but when I try to run something it complains that ``rmw_create_publisher`` is not defined in ``librmw_cyclonedds_cpp.dylib``. So I guess that where gcc/ELF/Linux decides to expand the template and provide the definition, clang/Mach-O/macOS decides not to expand it.

Fortunately, there is now this: https://github.com/ros2/rmw/issues/188#issuecomment-542937557. Would you be willing to change ``rmw_cyclonedds`` to use that instead?

Then you can get the credit for fixing things, as is only right :)

**Comment by rotu** [comment]
I’m on it. I think the weirdness on Mac is that the template definition is in an object file, whereas usually template definitions are in a header file. Oh well. I’ll make the change - it’s a minor modification on my #ifdef based attempt

**Pull request closed without merging**
